<a href="https://colab.research.google.com/github/JayanthiM12345/Portfolio-website/blob/main/Movie_Recommendation_System_using_machine_learning_with_pytohn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Data collection and preprocessing

In [11]:
#Loading data from csv file to pandas as dataframe
movies_data = pd.read_csv('/content/movies.csv')

In [12]:
#printing 5 rows of dataframe
movies_data.head()


index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [13]:
#num of rows and coloumns in dataframe
movies_data.shape

(4803, 24)

In [14]:
#selecting the relevent features for recommendation
selected_features = ['genres','keywords','tagline','title','cast']
print(selected_features)

['genres', 'keywords', 'tagline', 'title', 'cast']


In [15]:
#replacing the null values(missing values) with  null  string
for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')


In [16]:
#combining all the 5 selected feature
combined_features = movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['tagline']+' '+movies_data['title']+' '+movies_data['cast']

In [17]:
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  A newlywed couple's honeymoon ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      A New Yorker in Shanghai Shanghai Calling Da...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object


In [19]:
#converting the text data to feature vector(text to numerical data)
vectorizer = TfidfVectorizer()

In [20]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [21]:
print(feature_vectors)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 125710 stored elements and shape (4803, 17734)>
  Coords	Values
  (0, 241)	0.07702973509361205
  (0, 316)	0.08835496856391588
  (0, 5492)	0.10894353492251362
  (0, 13871)	0.10164285517330737
  (0, 5646)	0.10152445012366551
  (0, 3820)	0.20979668365154436
  (0, 3163)	0.217801279822015
  (0, 6070)	0.16035515092721375
  (0, 14697)	0.32868342477957735
  (0, 16997)	0.12182069797992155
  (0, 3330)	0.24478849760691077
  (0, 14591)	0.2064408541198997
  (0, 5150)	0.22271112105103313
  (0, 15631)	0.05416788004806317
  (0, 17423)	0.12295835183119022
  (0, 11405)	0.07643285197309059
  (0, 11726)	0.25770293500639957
  (0, 1112)	0.2797803115622773
  (0, 13643)	0.15647899138340024
  (0, 17433)	0.231874060207422
  (0, 17704)	0.19688224625205555
  (0, 13617)	0.2135481818946443
  (0, 14362)	0.2019893074404418
  (0, 17087)	0.1946062123874263
  (0, 14946)	0.16309249652718422
  :	:
  (4801, 17683)	0.2760175655193552
  (4801, 2501)	0.259189338670

In [22]:
#getting the similarity scores using cosine similarity
similarity= cosine_similarity(feature_vectors)

In [ ]:
print(similarity)

[[1.         0.33622781 0.26096609 ... 0.26614764 0.         0.18793274]
 [0.33622781 1.         0.25454511 ... 0.25652912 0.         0.17182781]
 [0.26096609 0.25454511 1.         ... 0.19299489 0.         0.14120104]
 ...
 [0.26614764 0.25652912 0.19299489 ... 1.         0.         0.14646562]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.18793274 0.17182781 0.14120104 ... 0.14646562 0.         1.        ]]


In [23]:
print(similarity.shape)

(4803, 4803)


Getting the movie name from the user

In [24]:
#getting the movie name from the user
movie_name = input('Enter your favourite movie name: ')

Enter your favourite movie name: avatar


In [25]:
#creating a liost with all the movie names given in the  dataset
list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [26]:
#finding the close match the movie given by the user
find_close_match = difflib.get_close_matches(movie_name,list_of_all_titles)
print(find_close_match)

['Avatar']


In [27]:
from os import close
close_match = find_close_match[0]
print(close_match)

Avatar


In [28]:
#find index of the movie with title
index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
print(index_of_the_movie)

0


In [29]:
#getting list of similar movies
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)


[(0, np.float64(1.0)), (1, np.float64(0.07591886080374775)), (2, np.float64(0.014253478296773203)), (3, np.float64(0.012767979054242828)), (4, np.float64(0.10551146005580832)), (5, np.float64(0.03655410266326125)), (6, np.float64(0.008149863201004758)), (7, np.float64(0.038829792611798385)), (8, np.float64(0.027974473126008512)), (9, np.float64(0.029347234900169637)), (10, np.float64(0.07197448206780956)), (11, np.float64(0.017306524132935236)), (12, np.float64(0.03330944022949719)), (13, np.float64(0.017464625495213798)), (14, np.float64(0.07141889709228842)), (15, np.float64(0.025925818872299618)), (16, np.float64(0.037103615429856296)), (17, np.float64(0.03150022303894457)), (18, np.float64(0.0540717612540435)), (19, np.float64(0.04237531505169045)), (20, np.float64(0.037081664171889926)), (21, np.float64(0.011272605022630765)), (22, np.float64(0.031367555555932666)), (23, np.float64(0.04121828861250702)), (24, np.float64(0.03856296237529012)), (25, np.float64(0.0)), (26, np.float64

In [30]:
len(similarity_score)

4803

In [31]:
#sorting the movies based on their similarity score
sorted_similar_movies = sorted(similarity_score,key = lambda x:x[1],reverse = True)
print(sorted_similar_movies)

[(0, np.float64(1.0)), (3158, np.float64(0.24478765201067407)), (94, np.float64(0.22698850325915837)), (56, np.float64(0.19336558388094843)), (1053, np.float64(0.19021710484487805)), (2403, np.float64(0.18522970705695777)), (1951, np.float64(0.1849169641006953)), (47, np.float64(0.18435604275655892)), (643, np.float64(0.17798856937932503)), (206, np.float64(0.17705636269787187)), (239, np.float64(0.17573277033206905)), (3730, np.float64(0.17415657670936996)), (838, np.float64(0.1701393782942416)), (661, np.float64(0.16989457885371914)), (1531, np.float64(0.1610178348137083)), (4593, np.float64(0.1602323589257827)), (1922, np.float64(0.15869416456703406)), (1354, np.float64(0.15663242980394235)), (812, np.float64(0.15641530542516413)), (2696, np.float64(0.14769264551780148)), (770, np.float64(0.142735066372275)), (461, np.float64(0.14196659120985164)), (1759, np.float64(0.13555530518400363)), (278, np.float64(0.1354944025148515)), (1976, np.float64(0.1299438778332114)), (1473, np.float6

In [32]:
#print the name of similar movies based on the index
print('Movies suggested for you: \n')

i=1
for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if(i<30):
    print(i, '.' ,title_from_index)
    i+=1

Movies suggested for you: 

1 . Avatar
2 . Alien
3 . Guardians of the Galaxy
4 . Star Trek Beyond
5 . Galaxy Quest
6 . Aliens
7 . Space Dogs
8 . Star Trek Into Darkness
9 . Space Cowboys
10 . Clash of the Titans
11 . Gravity
12 . Cargo
13 . Alien³
14 . Zathura: A Space Adventure
15 . Moonraker
16 . Trekkies
17 . Gettysburg
18 . Space Chimps
19 . Pocahontas
20 . Jason X
21 . Event Horizon
22 . Lost in Space
23 . The Right Stuff
24 . Planet of the Apes
25 . Muppets from Space
26 . The Astronaut's Wife
27 . Shadow Conspiracy
28 . Terminator Salvation
29 . Star Trek


Movie Recommendation system

In [33]:
movie_name = input('Enter your favourite movie name: ')

list_of_all_titles = movies_data['title'].tolist()

find_close_match = difflib.get_close_matches(movie_name,list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score,key = lambda x:x[1],reverse = True)
print('Movies suggested for you: \n')

i=1
for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if(i<30):
    print(i, '.' ,title_from_index)
    i+=1

Enter your favourite movie name: spectre
Movies suggested for you: 

1 . Spectre
2 . Skyfall
3 . The Incredibles
4 . Quantum of Solace
5 . Mission: Impossible - Ghost Protocol
6 . Johnny English Reborn
7 . Spy Kids: All the Time in the World
8 . Red Dragon
9 . Carnage
10 . The Green Hornet
11 . The Sorcerer's Apprentice
12 . Irreversible
13 . Water for Elephants
14 . Diamonds Are Forever
15 . The Legend of Tarzan
16 . Django Unchained
17 . The Girl with the Dragon Tattoo
18 . Remember Me, My Love
19 . I Spy
20 . Big Eyes
21 . Heavenly Creatures
22 . Inglourious Basterds
23 . RED 2
24 . Final Destination
25 . Escape Plan
26 . Tears of the Sun
27 . Harry Potter and the Order of the Phoenix
28 . GoldenEye
29 . Insurgent


# New Section